title: Notes & Historical Law Book Links
author: Rob Logue
theme: jekyll-theme-minimal  # Or try jekyll-theme-cayman, jekyll-theme-merlot for nicer looks
collections:
  notes:
    output: true
    permalink: /:slug/
