title: Notes & Historical Law Book Links
description: Common law notes and resources by Rob Logue
author: Rob Logue

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

collections_dir: content
collections:
  notes:
    output: true
    permalink: /:slug/