title: Notes & Historical Law Book Links
description: Common law notes and resources
author: Rob Logue

remote_theme: pages-themes/cayman@v0.2.0  # Forces the yellow background + white rounded tag buttons

plugins:
  - jekyll-remote-theme  # Required for remote_theme on GitHub Pages
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notes:
    output: true
    permalink: /:slug/